name: mobile
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  kartal: ^3.2.0
  device_preview: ^1.1.0

  # Core
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  vexana: ^3.5.1
  riverpod: ^2.3.6
  dio: ^5.3.0

  # Code Generator
  flutter_gen: ^5.3.1
  easy_localization: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/color/
    - assets/images/

flutter_gen:
  output: lib/product/generation/
  assets:
    enabled: true

  colors:
    inputs:
      - assets/color/colors.xml